# Set the project language
language: cpp

# Set test platforms
os:
  - osx
  - linux

# Use container-based infrastructure for Linux
sudo: false

# Add additional required packages for Linux
addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev

# Configuration
env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

# Run the build and the test
script:
  - ./posix-ci.sh

# Send notifications
notifications:
  email:
    - jacob@havoc.io
